-- TubeDigest Initial Database Schema
-- Created: 2025-11-18

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Summaries table: stores all video summaries
CREATE TABLE summaries (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  video_id TEXT NOT NULL UNIQUE,
  video_url TEXT NOT NULL,
  title TEXT,
  channel_name TEXT,
  thumbnail_url TEXT,
  duration INTEGER, -- in seconds
  summary_text TEXT NOT NULL,
  metadata JSONB DEFAULT '{}'::jsonb, -- stores additional video metadata
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Topics table: extracted topics from summaries
CREATE TABLE topics (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  summary_id UUID REFERENCES summaries(id) ON DELETE CASCADE,
  topic TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Mind maps table: stores mind map data for summaries
CREATE TABLE mind_maps (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  summary_id UUID REFERENCES summaries(id) ON DELETE CASCADE,
  nodes JSONB NOT NULL, -- React Flow nodes data
  edges JSONB NOT NULL, -- React Flow edges data
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes for better query performance
CREATE INDEX idx_summaries_video_id ON summaries(video_id);
CREATE INDEX idx_summaries_created_at ON summaries(created_at DESC);
CREATE INDEX idx_topics_summary_id ON topics(summary_id);
CREATE INDEX idx_topics_topic ON topics(topic);
CREATE INDEX idx_mind_maps_summary_id ON mind_maps(summary_id);

-- Full-text search index on summary text
CREATE INDEX idx_summaries_search ON summaries USING GIN(to_tsvector('english', summary_text));

-- Row Level Security (RLS) Policies
ALTER TABLE summaries ENABLE ROW LEVEL SECURITY;
ALTER TABLE topics ENABLE ROW LEVEL SECURITY;
ALTER TABLE mind_maps ENABLE ROW LEVEL SECURITY;

-- Allow public read access (anyone can view summaries)
CREATE POLICY "Public summaries are viewable by everyone" 
  ON summaries FOR SELECT 
  USING (true);

CREATE POLICY "Public topics are viewable by everyone" 
  ON topics FOR SELECT 
  USING (true);

CREATE POLICY "Public mind maps are viewable by everyone" 
  ON mind_maps FOR SELECT 
  USING (true);

-- Allow public insert (anyone can create summaries - you may want to restrict this later)
CREATE POLICY "Anyone can create summaries" 
  ON summaries FOR INSERT 
  WITH CHECK (true);

CREATE POLICY "Anyone can create topics" 
  ON topics FOR INSERT 
  WITH CHECK (true);

CREATE POLICY "Anyone can create mind maps" 
  ON mind_maps FOR INSERT 
  WITH CHECK (true);

-- Function to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Triggers to automatically update updated_at
CREATE TRIGGER update_summaries_updated_at 
  BEFORE UPDATE ON summaries 
  FOR EACH ROW 
  EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_mind_maps_updated_at 
  BEFORE UPDATE ON mind_maps 
  FOR EACH ROW 
  EXECUTE FUNCTION update_updated_at_column();

-- Comments for documentation
COMMENT ON TABLE summaries IS 'Stores YouTube video summaries generated by Claude';
COMMENT ON TABLE topics IS 'Extracted topics from video summaries for categorization';
COMMENT ON TABLE mind_maps IS 'Mind map visualizations for video summaries using React Flow';
COMMENT ON COLUMN summaries.metadata IS 'Additional metadata like view count, likes, tags, etc.';
